SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (1, N'Транспорт', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (2, N'Автомобили', 1)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (3, N'Мотоциклы и мототехника', 1)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (4, N'Грузовые и спецтехника', 1)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (5, N'Водный транспорт', 1)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (6, N'Запчасти и аксессуары', 1)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (7, N'Недвижимость', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (8, N'Квартиры', 7)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (9, N'Комнаты', 7)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (10, N'Дома, дачи, коттеджи', 7)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (11, N'Земельные участки', 7)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (12, N'Гаражи и машиноместа', 7)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (13, N'Коммерческая недвижимость', 7)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (14, N'Недвижимость за рубежом', 7)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (15, N'Работа', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (16, N'Вакансии', 15)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (17, N'Резюме', 15)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (18, N'Услуги', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (19, N'Предложение услуг', 18)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (20, N'Личные вещи', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (21, N'Одежда, обувь, аксессуары', 20)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (24, N'Детская одежда и обувь', 20)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (25, N'Товары для детей и игрушки', 20)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (26, N'Часы и украшения', 20)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (27, N'Красота и здоровье', 20)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (28, N'Для дома и дачи', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (29, N'Бытовая техника', 28)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (31, N'Мебель и интерьер', 28)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (32, N'Посуда и товары для кухни', 28)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (33, N'Продукты питания', 28)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (34, N'Ремонт и строительство ', 28)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (35, N'Растения ', 28)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (36, N'Бытовая электроника', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (37, N'Аудио и видео', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (38, N'Игры, приставки и программы', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (39, N'Настольные компьютеры', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (40, N'Ноутбуки ', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (41, N'Оргтехника и расходники', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (42, N'Планшеты и электронные книги ', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (43, N'Телефоны ', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (44, N'Товары для компьютера', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (45, N'Фототехника ', 36)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (46, N'Хобби и отдых ', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (47, N'Билеты и путешествия ', 46)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (48, N'Велосипеды ', 46)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (49, N'Книги и журналы ', 46)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (50, N'Коллекционирование ', 46)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (51, N'Музыкальные инструменты ', 46)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (52, N'Охота и рыбалка ', 46)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (53, N'Спорт и отдых ', 46)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (54, N'Животные ', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (55, N'Собаки ', 54)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (56, N'Кошки', 54)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (57, N'Птицы', 54)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (58, N'Аквариум', 54)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (59, N'Другие животные ', 54)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (60, N'Товары для животных', 54)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (61, N'Для бизнеса', NULL)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (62, N'Готовый бизнес ', 61)
INSERT INTO [dbo].[Categories] ([Id], [Name], [ParentCategoryId]) VALUES (63, N'Оборудование для бизнеса', 61)
SET IDENTITY_INSERT [dbo].[Categories] OFF
