INSERT INTO [dbo].[regions] ([id], [name]) VALUES (0, N'Москва и Московская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (1, N'Санкт-Петербург и область')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (2, N'Адыгея')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (3, N'Алтайский край')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (4, N'Амурская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (5, N'Архангельская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (6, N'Астраханская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (7, N'Башкортостан(Башкирия)')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (8, N'Белгородская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (9, N'Брянская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (10, N'Бурятия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (11, N'Владимирская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (12, N'Волгоградская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (13, N'Вологодская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (14, N'Воронежская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (15, N'Дагестан')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (16, N'Еврейская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (17, N'Ивановская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (18, N'Иркутская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (19, N'Кабардино-Балкария')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (20, N'Калининградская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (21, N'Калмыкия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (22, N'Калужская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (23, N'Камчатская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (24, N'Карелия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (25, N'Кемеровская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (26, N'Кировская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (27, N'Коми')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (28, N'Костромская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (29, N'Краснодарский край')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (30, N'Красноярский край')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (31, N'Курганская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (32, N'Курская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (33, N'Липецкая обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (34, N'Магаданская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (35, N'Марий Эл')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (36, N'Мордовия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (37, N'Мурманская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (38, N'Нижегородская (Горьковская)')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (39, N'Новгородская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (40, N'Новосибирская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (41, N'Омская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (42, N'Оренбургская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (43, N'Орловская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (44, N'Пензенская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (45, N'Пермский край')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (46, N'Приморский край')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (47, N'Псковская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (48, N'Ростовская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (49, N'Рязанская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (50, N'Самарская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (51, N'Саратовская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (52, N'Саха (Якутия)')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (53, N'Сахалин')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (54, N'Свердловская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (55, N'Северная Осетия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (56, N'Смоленская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (57, N'Ставропольский край')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (58, N'Тамбовская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (59, N'Татарстан')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (60, N'Тверская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (61, N'Томская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (62, N'Тува (Тувинская Респ.)')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (63, N'Тульская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (64, N'Тюменская обл. и Ханты-Мансийский АО')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (65, N'Удмуртия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (66, N'Ульяновская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (67, N'Уральская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (68, N'Хабаровский край')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (69, N'Хакасия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (70, N'Челябинская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (71, N'Чечено-Ингушетия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (72, N'Читинская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (73, N'Чувашия')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (74, N'Чукотский АО')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (75, N'Ямало-Ненецкий АО')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (76, N'Ярославская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (77, N'Карачаево-Черкесская Республика')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (78, N'Винницкая обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (79, N'Волынская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (80, N'Днепропетровская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (81, N'Донецкая обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (82, N'Житомирская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (83, N'Закарпатская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (84, N'Запорожская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (85, N'Ивано-Франковская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (86, N'Киевская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (87, N'Кировоградская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (88, N'Крым АР.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (89, N'Луганская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (90, N'Львовская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (91, N'Николаевская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (92, N'Одесская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (93, N'Полтавская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (94, N'Ровенская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (95, N'Сумская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (96, N'Тернопольская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (97, N'Украина')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (98, N'Харьковская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (99, N'Херсонская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (100, N'Хмельницкая обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (101, N'Черкасская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (102, N'Черниговская обл.')
INSERT INTO [dbo].[regions] ([id], [name]) VALUES (103, N'Черновицкая обл.')
