SET IdENTITY_INSERT [dbo].[Regions] ON
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (1, N'Москва и Московская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (2, N'Санкт-Петербург и область')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (3, N'Адыгея')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (4, N'Алтайский край')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (5, N'Амурская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (6, N'Архангельская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (7, N'Астраханская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (8, N'Башкортостан(Башкирия)')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (9, N'Белгородская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (10, N'Брянская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (11, N'Бурятия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (12, N'Владимирская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (13, N'Волгоградская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (14, N'Вологодская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (15, N'Воронежская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (16, N'Дагестан')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (17, N'Еврейская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (18, N'Ивановская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (19, N'Иркутская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (20, N'Кабардино-Балкария')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (21, N'Калининградская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (22, N'Калмыкия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (23, N'Калужская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (24, N'Камчатская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (25, N'Карелия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (26, N'Кемеровская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (27, N'Кировская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (28, N'Коми')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (29, N'Костромская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (30, N'Краснодарский край')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (31, N'Красноярский край')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (32, N'Курганская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (33, N'Курская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (34, N'Липецкая обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (35, N'Магаданская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (36, N'Марий Эл')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (37, N'Мордовия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (38, N'Мурманская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (39, N'Нижегородская (Горьковская)')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (40, N'Новгородская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (41, N'Новосибирская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (42, N'Омская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (43, N'Оренбургская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (44, N'Орловская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (45, N'Пензенская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (46, N'Пермский край')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (47, N'Приморский край')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (48, N'Псковская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (49, N'Ростовская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (50, N'Рязанская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (51, N'Самарская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (52, N'Саратовская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (53, N'Саха (Якутия)')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (54, N'Сахалин')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (55, N'Свердловская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (56, N'Северная Осетия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (57, N'Смоленская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (58, N'Ставропольский край')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (59, N'Тамбовская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (60, N'Татарстан')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (61, N'Тверская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (62, N'Томская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (63, N'Тува (Тувинская Респ.)')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (64, N'Тульская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (65, N'Тюменская обл. и Ханты-Мансийский АО')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (66, N'Удмуртия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (67, N'Ульяновская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (68, N'Уральская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (69, N'Хабаровский край')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (70, N'Хакасия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (71, N'Челябинская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (72, N'Чечено-Ингушетия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (73, N'Читинская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (74, N'Чувашия')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (75, N'Чукотский АО')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (76, N'Ямало-Ненецкий АО')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (77, N'Ярославская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (78, N'Карачаево-Черкесская Республика')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (79, N'Винницкая обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (80, N'Волынская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (81, N'Днепропетровская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (82, N'Донецкая обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (83, N'Житомирская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (84, N'Закарпатская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (85, N'Запорожская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (86, N'Ивано-Франковская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (87, N'Киевская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (88, N'Кировоградская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (89, N'Крым АР.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (90, N'Луганская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (91, N'Львовская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (92, N'Николаевская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (93, N'Одесская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (94, N'Полтавская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (95, N'Ровенская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (96, N'Сумская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (97, N'Тернопольская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (98, N'Украина')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (99, N'Харьковская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (100, N'Херсонская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (101, N'Хмельницкая обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (102, N'Черкасская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (103, N'Черниговская обл.')
INSERT INTO [dbo].[Regions] ([Id], [Name]) VALUES (104, N'Черновицкая обл.')
SET IdENTITY_INSERT [dbo].[Regions] OFF
